# Generated by Django 6.0.7 on 2026-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tv_symbol',
            field=models.CharField(blank=True, help_text='TradingView symbol e.g. BINANCE:BTCUSDT, OANDA:XAUUSD, NASDAQ:AAPL', max_length=50),
        ),
    ]
