# Generated by Django 6.0.7 on 2026-07-20 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('lot_size', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('outcome', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('be', 'Break Even'), ('open', 'Still Open')], default='open', max_length=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rr_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('setup_notes', models.TextField(blank=True, help_text='Why did you take this trade?')),
                ('lesson', models.TextField(blank=True, help_text='What did you learn?')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='core_tradej_user_id_395d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('tv_symbol', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
